### ISSUE TITLE
Error: Could not open the site: http://graph4code.whyis.io/

### ISSUE THREAD

**Issue by a825335172** [wala/graph4code#13]
Hello, I saw and read your paper and think it is very enlightening and nice. And I have imported the generated sample knowledge graph into the Apeach jena database. I found that the URI website(http://graph4code.whyis.io/)(http://purl.org/twc/graph4code/python) for the function/module is no longer valid. Is there a description of the function/module on that website or anything like that? I'm very curious about this. If you can reply me, I can be very grateful you !

**Comment by ibrahimabdelaziz** [comment]
Hi, 
We used _whyis_ at the beginning of this project for visualizing and serving the graph. Now, we no longer use it and use Apache Jena instead.

Since you have Jena already installed, you can use its query interface to retrieve whatever data you wanted. Here are some sample queries you may use https://wala.github.io/graph4code/example_queries.html. The schema itself is at https://wala.github.io/graph4code/

**Comment by a825335172** [comment]
Thank you very much. Really appreciate your work.
